public class ACE_Constants {
   public static final String ACC_TYPE_PROSPECT = 'Prospect';
   public static final String ACC_TYPE_CUSTOMER = 'Customer';
   public static final String ASSET_STATUS_PURCHASED = 'Purchased';
   public static final String OPTY_STAGE_CLOSED_WON = 'Closed Won';
   public static final String OPTY_STAGE_CLOSED_Lost = 'Closed Lost';
   public static final String OPTY_STAGE_Enquiry = 'Enquiry';
   public static final String TASK_Status_Open = 'Open';
   public static final String OPP_Stage_Name_Booking = 'Booking';
   public static final String OPP_Enquiry_Type_FLD = 'FLD';
   public static final String OPP_Enquiry_Source_NWP = 'NWP';
   public static final String leadDealerRecType      = 'Dealer Leads';
    
    /*************************SAGAR****************************************** */
    public static final String ACE_SOURCE_MITRA = 'mitra'; 
     public static final String ACC_MRC = 'MRC';
    
    
    /*************************************************************************/
    
    /************************ Mrinal *************************************** */
    public static final String API_RESPONSE_STATUS_SUCCESS = 'success';
    public static final String API_RESPONSE_STATUS_ERROR = 'error';
    public static final String API_RESPONSE_STATUS_EXCEPTION = 'exception';
    public static final String NAV_MENU_ITEM_STATUS_LIVE = 'Live';
    public static final String API_RESPONSE_TYPE_SALESFORCEOBJECT = 'SalesforceObject';
    /*********************************************************************** */
    
    /************************ SHAILENDRA *************************************** */
    public static final String ACE_BookingPDFPage_Path = '/apex/BookingPDF';
    /*********************************************************************** */
}