/**
 * ─────────────────────────────────────────────────────────────────────────────────────────────────┐
 * Summary :Utility class.
 * ──────────────────────────────────────────────────────────────────────────────────────────────────
 * @author         Susidharthak Mahapatra   <susidharthak.mahapatra@pwc.com>
 * @modifiedy      Susidharthak Mahapatra   <susidharthak.mahapatra@pwc.com>
 * @maintainedBy   Susidharthak Mahapatra   <susidharthak.mahapatra@pwc.com>
 * @version        1.0
 * @created        2019-11-26
 * @modified       Susidharthak Mahapatra   <susidharthak.mahapatra@pwc.com>
 * @systemLayer    
 * @see            ????
 * @see            ????
 * ──────────────────────────────────────────────────────────────────────────────────────────────────
 * @changes
 * v0.1            susidharthak.mahapatra@pwc.com
 * 2019-11-26      Explanation of the change.  Multiple lines can be used to explain the change, but
 *                 each line should be indented till left aligned with the previous description text.

 * ─────────────────────────────────────────────────────────────────────────────────────────────────┘
 */

//*****************************************Service*************************************************************

@RestResource(urlMapping='/pushPreLaunchLeadstoSF/*') 
global class ACE_createPreLaunchLeads {
    
    @HttpPost
    global static void pushLeadsintoSF(){
        
    }
}